name: ipwhois
description: A Dart package for retrieving some information about IP that is connected to the internet. such as  city & country name, continent code, latitude and longitude, IP v4 or v6.
version: 1.1.0
homepage: https://github.com/shervin-h/ipwhois
repository: https://github.com/shervin-h/ipwhois
issue_tracker: https://github.com/shervin-h/ipwhois/issues

environment:
  sdk: ^3.3.0

dependencies:
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
